# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
vector_zeros =np.zeros(10)
print(vector_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
# Q_3 method No. 1
vector_10_to_49 = np.arange(10, 49)
print(vector_10_to_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [4]:
# Q_3 method No. 2
vector_10_to_49 = 10 + np.arange(39)
vector_10_to_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [5]:
vector_10_to_49.shape

(39,)

5. Print the type of the previous array in question 3

In [6]:
print(vector_10_to_49.dtype)

int32


6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.__config__)

1.19.2
<module 'numpy.__config__' from 'C:\\Users\\Shoaib\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


7. Print the dimension of the array in question 3


In [8]:
vector_10_to_49.ndim

1

8. Create a boolean array with all the True values

In [9]:
arr_trues = np.ones(10, dtype='bool')
print(arr_trues)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [10]:
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("No. of Dimensions: ", arr_2d.ndim)
print(arr_2d)

No. of Dimensions:  2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
# second method to create a 2-D arrary
arr_2d_ = np.array([[i for i in range(1, 6)] for j in range(2)])
print("No. of Dimensions: ", arr_2d_.ndim)
print(arr_2d_)

No. of Dimensions:  2
[[1 2 3 4 5]
 [1 2 3 4 5]]


10. Create a three dimensional array



In [12]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [6, 7, 8]]])
print("No. of Dimensions: ", arr_3d.ndim)
print(arr_3d)

No. of Dimensions:  3
[[[1 2 3]
  [4 5 6]
  [6 7 8]]]


In [13]:
# second method to create a 3-D arrary
arr_3d_ = np.array([[[i for i in range(1, 5)] for j in range(1, 3)] for k in range(1, 4)])
print("No. of Dimensions: ", arr_3d_.ndim)
print(arr_3d_)

No. of Dimensions:  3
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [14]:
v = np.arange(1, 10)
print("Original Vector: ", v)
print('*********************')
print("Reversed Vector: ", v[::-1])

Original Vector:  [1 2 3 4 5 6 7 8 9]
*********************
Reversed Vector:  [9 8 7 6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [15]:
null_1 = (np.arange(10) == 4).astype(int)
null_1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [16]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [17]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(float)
print(arr.dtype)

float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [18]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr1.dot(arr2.T)) # take transpose of arr2 with .T

[[ 11.  47.]
 [ 26. 110.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [19]:
np.maximum(arr1, arr2)

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

In [20]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

# comparing each element of arr1 and arr2 and taking the greater one
arr3 = np.maximum(arr1, arr2)
print(arr3)

[[ 1.  4.  3.]
 [ 7.  5. 12.]]


17. Extract all odd numbers from arr with values(0-9)

In [21]:
arr = np.arange(0, 10)
arr_odd = arr[arr % 2 != 0]
print(arr_odd)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [22]:
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [23]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [24]:
x = np.ones((5, 5))
print("Original array: ")
print(x)
print('*********************')
print("Printing 0's inside array: ")
x[1:-1, 1:-1] = 0
print(x)

Original array: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
*********************
Printing 0's inside array: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [25]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print([[i if i!=5 else 12 for i in j] for j in arr2d])

[[1, 2, 3], [4, 12, 6], [7, 8, 9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [26]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Original array: \n", arr3d, '\n****************')
arr3d[0:1, 0]= 64
print("Modified array: \n", arr3d)

Original array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
****************
Modified array: 
 [[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [27]:
arr2d = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print("Original array: \n", arr2d, "\n*******************")
print("Sliced array: \n", arr2d[0:1, :])

Original array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 
*******************
Sliced array: 
 [[0 1 2 3 4]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [28]:
arr2d = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print("Original array: \n", arr2d, "\n*******************")
print("Sliced 2nd value from 2nd 1-D array: \n", arr2d[1, 1])

Original array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 
*******************
Sliced 2nd value from 2nd 1-D array: 
 6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [29]:
arr2d = np.arange(10).reshape(2,5)
print("Original array: \n", arr2d, "\n*******************")
print("Sliced array: \n", arr2d[0:2, 2:3])

Original array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 
*******************
Sliced array: 
 [[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [30]:
arr_10x10 = np.random.randn(10, 10)
print("Max value: ", np.max(arr_10x10))
print("Min value: ", np.min(arr_10x10))

Max value:  3.268563458976643
Min value:  -3.1285223196766334


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Common items in a and b are: ", np.intersect1d(a, b))

Common items in a and b are:  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [32]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Positions where items of a and b matches are: ", list(np.flatnonzero(np.in1d(a, b))))

Positions where items of a and b matches are:  [1, 3, 5, 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

In [34]:
print("Names array: \n", names)
print("Random data array: \n", data)

Names array: 
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Random data array: 
 [[-1.19925047 -0.45298434 -0.31318204  1.50089984]
 [ 0.04699984  1.13470169  0.29443432  1.56863951]
 [-0.97287738 -1.51148305 -0.19682394 -0.47022692]
 [ 0.97178815 -0.74172305 -1.01009762  1.17598659]
 [-1.4116423   0.54217684  0.30025602  0.89807092]
 [ 0.98647231 -2.48030603 -0.148557   -0.97676741]
 [-0.22812191 -0.36618388 -0.11222707  0.30777968]]


In [35]:
names != "Will"

array([ True,  True, False,  True, False,  True,  True])

In [36]:
data[names != "Will"]

array([[-1.19925047, -0.45298434, -0.31318204,  1.50089984],
       [ 0.04699984,  1.13470169,  0.29443432,  1.56863951],
       [ 0.97178815, -0.74172305, -1.01009762,  1.17598659],
       [ 0.98647231, -2.48030603, -0.148557  , -0.97676741],
       [-0.22812191, -0.36618388, -0.11222707,  0.30777968]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [37]:
mask = (names != "Will") & (names != "Joe")
data[mask]

array([[-1.19925047, -0.45298434, -0.31318204,  1.50089984],
       [ 0.97178815, -0.74172305, -1.01009762,  1.17598659]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [38]:
# Q 31 method No. 1
arr = np.random.randint(low=1, high=15, size=(5,3)) + np.random.randn(5,3)
arr

array([[ 3.04267353,  8.99558375, 11.90771802],
       [ 9.48287814, 13.15624782, 16.19942376],
       [ 1.290041  ,  6.91920884,  1.47252779],
       [ 3.36663427, 13.72660328,  2.80294596],
       [13.12226544,  8.25592384,  8.02487674]])

In [39]:
# Q 31 method No. 2
np.random.uniform(low=1, high=15, size=(5,3))

array([[ 6.16439408,  1.57145865, 13.96225537],
       [ 3.86215343,  9.20129482,  5.18462914],
       [ 4.68588415,  7.55164826, 10.74285032],
       [ 6.60079169,  9.4639852 ,  7.66152692],
       [12.74431558,  1.53718171, 12.30892488]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [40]:
Q_32_array = np.random.uniform(low=1, high=16, size=(2,2,4))
Q_32_array

array([[[15.97935475,  9.39354549,  5.18335511, 14.55948604],
        [12.21100704, 10.80121294,  8.93554892,  4.54646029]],

       [[15.41920105,  9.5880126 ,  4.66912024, 13.8700947 ],
        [10.96863394,  4.82471956, 10.67015037, 14.18130956]]])

33. Swap axes of the array you created in Question 32

In [41]:
# Q 33 method No. 1
Q_32_array.reshape(4,2,2)

array([[[15.97935475,  9.39354549],
        [ 5.18335511, 14.55948604]],

       [[12.21100704, 10.80121294],
        [ 8.93554892,  4.54646029]],

       [[15.41920105,  9.5880126 ],
        [ 4.66912024, 13.8700947 ]],

       [[10.96863394,  4.82471956],
        [10.67015037, 14.18130956]]])

In [42]:
# Q 33 method No. 2
np.swapaxes(Q_32_array, 2, 2)

array([[[15.97935475,  9.39354549,  5.18335511, 14.55948604],
        [12.21100704, 10.80121294,  8.93554892,  4.54646029]],

       [[15.41920105,  9.5880126 ,  4.66912024, 13.8700947 ],
        [10.96863394,  4.82471956, 10.67015037, 14.18130956]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [43]:
Q_34_array = np.arange(0, 2, 0.2)
print("Original array: ", Q_34_array)
Q_34_array = np.array([np.sqrt(i) for i in Q_34_array])
Q_34_array[Q_34_array < 0.5] = 0
print("Array after replacing values less than 0.5: \n", Q_34_array)

Original array:  [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
Array after replacing values less than 0.5: 
 [0.         0.         0.63245553 0.77459667 0.89442719 1.
 1.09544512 1.18321596 1.26491106 1.34164079]


In [44]:
Q_34_arr2 = np.array([np.sqrt(i) for i in np.random.uniform(low=0, high=1, size=(1, 10))])
np.array([[i if i>=0.5 else 0 for i in j] for j in Q_34_arr2])

#print([[i if i!=5 else 12 for i in j] for j in arr2d])

array([[0.73920282, 0.76476572, 0.88110301, 0.85498616, 0.78634472,
        0.        , 0.        , 0.67024512, 0.9154593 , 0.63174727]])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [45]:
a = np.random.randn(12)
b = np.random.randn(12)

In [46]:
np.array(np.maximum(a, b))

array([ 0.2256277 , -0.32278303,  0.83113727, -0.85329061,  1.11949193,
       -0.28974193,  0.64152819, -0.31030013,  1.10525801,  0.20782336,
        0.8092493 , -0.21886702])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [48]:
# Q_37 method No. 1
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [49]:
# Q_37 method No. 2
mask = np.in1d(a, b)
a = a[~mask]
print(a)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [50]:
# Q_38 method No. 1
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[0:, 1] = newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [51]:
# Q_38 method No. 2
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.delete(sampleArray, 1, 1)
sampleArray= np.insert(sampleArray, 1, newColumn, axis=1)
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [52]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print("x: \n", x)
print("y: \n", y)

x: 
 [[1. 2. 3.]
 [4. 5. 6.]]
y: 
 [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


In [53]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [54]:
import random
random_matrix = np.array([[random.random() for i in range(5)] for j in range(4)])

In [55]:
random_matrix

array([[0.38810979, 0.54063172, 0.32785081, 0.91649661, 0.59746689],
       [0.14046569, 0.39901374, 0.16193407, 0.67170244, 0.1602587 ],
       [0.76617724, 0.27970375, 0.57873069, 0.61108593, 0.53132934],
       [0.24650202, 0.01216816, 0.31761811, 0.13898597, 0.45754244]])

In [56]:
np.cumsum(random_matrix, axis=0)

array([[0.38810979, 0.54063172, 0.32785081, 0.91649661, 0.59746689],
       [0.52857548, 0.93964545, 0.48978487, 1.58819904, 0.75772559],
       [1.29475272, 1.21934921, 1.06851557, 2.19928497, 1.28905493],
       [1.54125473, 1.23151736, 1.38613368, 2.33827095, 1.74659737]])