# Numpy_Assignment_2

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr1d = np.arange(10)
print("Array dimensions before conversion: ", arr1d.ndim)
print("Original array: ", arr1d)
print("***********************************************")
arr2d = arr1d.reshape(-1,5)
print("Array dimensions after conversion: ", arr2d.ndim)
print("1D array converted to 2D: \n", arr2d)

Array dimensions before conversion:  1
Original array:  [0 1 2 3 4 5 6 7 8 9]
***********************************************
Array dimensions after conversion:  2
1D array converted to 2D: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1 = np.arange(10).reshape(-1, 5)
arr2 = np.ones(10).reshape(-1, 5)
print("Stacking arr1 and arr2 vertically")
np.vstack((arr1, arr2)).astype(int)

Stacking arr1 and arr2 vertically


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr3 = np.arange(10).reshape(-1, 5)
arr4 = np.ones(10).reshape(-1, 5)
print("Stacking arr3 and arr4 horizontally")
np.hstack((arr3, arr4)).astype(int)

Stacking arr3 and arr4 horizontally


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr_of_array = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])
arr_of_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
# methos 1
arr_of_array.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# method 2
arr_of_array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# method 3
arr_of_array.reshape(-1,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [8]:
arr_nd_to_1d = np.arange(15).reshape((1, 1, 5, 3, 1, 1))
print("Dimensions are: ", arr_nd_to_1d.ndim)

Dimensions are:  6


In [9]:
# method 1
print("Converting 6-D array to 1-D")
arr_nd_to_1d.ravel()

Converting 6-D array to 1-D


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
print("Converting 6-D array to 1-D")
arr_nd_to_1d.flatten()

Converting 6-D array to 1-D


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
print("Converting 6-D array to 1-D")
arr_nd_to_1d.reshape(-1,)

Converting 6-D array to 1-D


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [12]:
arr_1d_to_nd = np.arange(15).reshape(-1,)
print("Array dimenions before: ", arr_1d_to_nd.ndim)

Array dimenions before:  1


In [13]:
arr_1d_to_nd = arr_1d_to_nd.reshape(5,3)
print("Array dimensions after: ", arr_1d_to_nd.ndim)
arr_1d_to_nd

Array dimensions after:  2


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [14]:
arr_sqr = np.arange(1, 26).reshape(5, 5)
print("Array shape: ", arr_sqr.shape)
print(arr_sqr)

Array shape:  (5, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
print("Finding square of array")
np.square(arr_sqr)

Finding square of array


array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [16]:
arr_mean = np.arange(1, 31).reshape(5, 6)
print("Array shape: ", arr_mean.shape)
print(arr_mean)

Array shape:  (5, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [17]:
print("mean of array created above is: ", arr_mean.mean())

mean of array created above is:  15.5


In [18]:
np.mean(arr_mean)

15.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [19]:
arr_mean.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [20]:
np.median(arr_mean)

15.5

## Question:11

### Find the transpose of the previous array in Q8?

In [21]:
# method 1
arr_mean.T

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

In [22]:
# method 2
np.transpose(arr_mean)

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [23]:
arr_diag = np.arange(1, 17).reshape(4, 4)
print("Array shape is: ", arr_diag.shape)
print(arr_diag)

Array shape is:  (4, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [24]:
print("Sum of array diagonal is: ", np.trace(arr_diag))

Sum of array diagonal is:  34


## Question:13

### Find the determinant of the previous array in Q12?

In [25]:
np.linalg.det(arr_diag)

-1.820448242817726e-31

## Question:14

### Find the 5th and 95th percentile of an array?

In [26]:
arr_percentile = np.arange(1, 11)
arr_percentile

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
print("5th percentile of array is: ", np.percentile(arr_percentile, 5))

5th percentile of array is:  1.4500000000000002


In [28]:
print("95th percentile of array is: ", np.percentile(arr_percentile, 95))

95th percentile of array is:  9.549999999999999


## Question:15

### How to find if a given array has any null values?

In [29]:
arr_nan = np.arange(1, 16).reshape(3, 5)
# replace odd numbers with nan
arr_nan = np.where(arr_nan % 2 != 0, np.NaN, arr_nan)
arr_nan

array([[nan,  2., nan,  4., nan],
       [ 6., nan,  8., nan, 10.],
       [nan, 12., nan, 14., nan]])

In [30]:
np.isnan(arr_nan)

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [31]:
print("Number of NaN values are: ", np.sum(np.isnan(arr_nan)))

Number of NaN values are:  8
