# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [1]:
#type your code here
import numpy as np

2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [2]:
#type your code here
cupcakes = np.array([2, 0.75, 2, 1, 0.5])
cupcakes

array([2.  , 0.75, 2.  , 1.  , 0.5 ])

3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [3]:
#type your code here
recipies = np.genfromtxt('recipes.csv', delimiter=',')
recipies

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [4]:
#type your code here
ingredients = np.array(['Cups of Flour', 'Cups of Sugar', 'Eggs', 'Cups of Milk', 'Cups of Butter'])
recipies_name = np.array(['Cupcakes', 'Pancake', 'Cookie', 'Bread'])

In [5]:
recipies_ingredients = np.vstack((np.hstack(('Recipes', ingredients)), 
                                  np.hstack((recipies_name.reshape(-1, 1), recipies))))
print(recipies_ingredients)

[['Recipes' 'Cups of Flour' 'Cups of Sugar' 'Eggs' 'Cups of Milk'
  'Cups of Butter']
 ['Cupcakes' '2.0' '0.75' '2.0' '1.0' '0.5']
 ['Pancake' '1.0' '0.125' '1.0' '1.0' '0.125']
 ['Cookie' '2.75' '1.5' '1.0' '0.0' '1.0']
 ['Bread' '4.0' '0.5' '2.0' '2.0' '0.5']]


5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [6]:
#type your code here
eggs = recipies[:, 2]
eggs

array([2., 1., 1., 2.])

6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [7]:
#type your code here
recipies_name[eggs == 1]

array(['Pancake', 'Cookie'], dtype='<U8')

7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [8]:
#type your code here
cookies = recipies[2,:]
cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [9]:
#type your code here
double_batch_cupcakes = cupcakes * 2
double_batch_cupcakes

array([4. , 1.5, 4. , 2. , 1. ])

9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [10]:
#type your code here
grocery_list = np.array([cookies, double_batch_cupcakes])

In [11]:
grocery_list

array([[2.75, 1.5 , 1.  , 0.  , 1.  ],
       [4.  , 1.5 , 4.  , 2.  , 1.  ]])